import exp from 'constants';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const OpenAI = require("@langchain/openai").OpenAI;
const PromptTemplate = require("@langchain/core/prompts").PromptTemplate;
const CommaSeparatedListOutputParser = require("@langchain/core/output_parsers").CommaSeparatedListOutputParser;
const RunnableSequence = require("@langchain/core/runnables").RunnableSequence;
const dotenv= require('dotenv')

dotenv.config()

//Generate ideas for apis from schema
//takes in schema generated by langchain and query by user
const getAPIIdeas = async (schema) => {
  // With a `CommaSeparatedListOutputParser`, we can parse a comma separated list.
  console.log(schema)
  const parser = new CommaSeparatedListOutputParser();

  const chain = RunnableSequence.from([
    PromptTemplate.fromTemplate("Give me a comma separated list of API Ideas with to create an API based on a JSON schema of the data. These must be only GET style read only APIs. Be specific with API ideas and make them complex queries. Include the API Name, and make API names specific. This is the JSON Schema to base your list off of: {schema} Only include API ideas that could be created based on the JSON schema. Create as many as you can think of. \n{format_instructions}"),
    new OpenAI({ temperature: 0.4, maxTokens:3000, modelName: "gpt-4"}),
    parser,
  ]);

  console.log("running chain")

  let response = await chain.invoke({
    schema: JSON.stringify(schema),
    format_instructions: "You must only return a comma separated list.",
  });



  return response; 

};


function formatIdeas(ideas){
  let returnArr =[]
  for(let idea of ideas){
    returnArr.push(idea.replace(/\n/g, ","))
  }
  return returnArr
}

export default getAPIIdeas;

